# Generated by Django 6.0.3 on 2026-04-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la salle')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('room_type', models.CharField(choices=[('AMPHI', 'Amphithéâtre'), ('LABO', 'Laboratoire Informatique'), ('TD', 'Salle de cours')], default='TD', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Projecteur')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Climatisation')),
            ],
        ),
    ]
