# Generated by Django 6.0.3 on 2026-04-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Salle',
        ),
    ]
