# Generated by Django 6.0.3 on 2026-04-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0002_rename_room_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la salle'),
        ),
    ]
