# Generated by Django 6.0.3 on 2026-04-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0003_salle_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salle',
            old_name='room_type',
            new_name='salle_type',
        ),
    ]
